version: '3.2'

services:

  espocrm-mariadb:
    container_name: espocrm-mariadb
    image: mariadb:latest # or mariadb:10.3.27
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1
    volumes:
      - ./mariadb/data:/var/lib/mysql

  espocrm-php:
    container_name: espocrm-php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
     - ./html:/var/www/html
     - ./logs:/var/log/apache2
    restart: unless-stopped
    ports:
      - 8080:80
